apiVersion: v1alpha
kind: Project
metadata:
  name: performous-web
spec:
  repository:
    url: "git@github.com:performous/web.git"
    run: true
    run_on:
      - branches
      - tags
    pipeline_file: ".semaphore/semaphore.yml"
    status:
      pipeline_files:
        - path: ".semaphore/semaphore.yml"
          level: "pipeline"